import { mkdir, cp, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const output = resolve(root, 'public');
if (output !== root + (process.platform === 'win32' ? '\\public' : '/public')) throw new Error('Unexpected output directory');
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
await cp(resolve(root, 'assets'), resolve(output, 'assets'), { recursive: true });
for (const file of ['index.html', 'admin.html', 'album-cilandak.html', 'album-dharmawangsa.html', 'album-dharmawangsa-residence.html']) await cp(resolve(root, file), resolve(output, file));
console.log('Built public website: 5 pages and assets. Server source and local tools excluded.');
